export const EXPORT_TABLE_AS_PPT_QUESTION = 'export table as ppt';
export const EXPORT_ABSTRACTS_AS_CSV = 'export abstracts';
export const EXPORT_ABSTRACTS_AS_CSV_TWO = 'export';
export const CUSTOM_QUESTIONS = [EXPORT_TABLE_AS_PPT_QUESTION, EXPORT_ABSTRACTS_AS_CSV, EXPORT_ABSTRACTS_AS_CSV_TWO];
